config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'events#index'
  resources :events
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :schedule
  has_many :shop
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :event
end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all.order(id: 'DESC')
  end

  def new
    @event = EventScheduleShop.new
  end

  def create
    @event = EventScheduleShop.new(event_schedule_shop_params)
    if @event.valid?
      @event.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])
  end
  private

  def event_schedule_shop_params
    params.require(:event_schedule_shop)
           .permit(:name, :description, :savetime, 
                  :savedate, :event_id, :shop_name, 
                  :shop_url, :map_url, :comment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/index.html.erb
<h1>トップページです</h1>

<div>
  <%= link_to '新規登録', new_event_path %>
</div>

<div>
  <% @events.each do |event| %>
    <div>
      <%= link_to event.name, event_path(event.id) %>
    </div>
  <% end %>
</div>

app/views/events/new.html.erb
<%= form_with  model: @event, url: events_path, local: true do |form| %>
  <%= form.text_field :name %>
  <%= form.text_area :description %>

  <%= form.date_field :savedate %>
  <%= form.select :savetime, ['00:00~', '00:30~', '01:00~'], {include_blank: '選択'}, class: 'date_time' %>

  <%= form.text_field :shop_name %>
  <%= form.text_field :shop_url %>
  <%= form.text_field :map_url %>
  <%= form.text_area :comment %>

  <%= form.submit %>
<% end %>

app/views/events/show.html.erb
<h1>詳細ページだよ</h1>
<%= @event.name %>
<%= @event.description %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ModalApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>